INSERT INTO `movement` (id, name) VALUES (1, 'Deadlift');
INSERT INTO `movement` (id, name) VALUES (2, 'Back Squat');
INSERT INTO `movement` (id, name) VALUES (3, 'Bench Press');
INSERT INTO `movement` (id, name) VALUES (4, 'Snatch');
INSERT INTO `movement` (id, name) VALUES (5, 'Clean and Jerk');
INSERT INTO `movement` (id, name) VALUES (6, 'Front Squat');
INSERT INTO `movement` (id, name) VALUES (7, 'Overhead Press');
INSERT INTO `movement` (id, name) VALUES (8, 'Pull-up');
INSERT INTO `movement` (id, name) VALUES (9, 'Push-up');
INSERT INTO `movement` (id, name) VALUES (10, 'Row');
INSERT INTO `movement` (id, name) VALUES (11, 'Sprint');
INSERT INTO `movement` (id, name) VALUES (12, 'Jump');
INSERT INTO `movement` (id, name) VALUES (13, 'Swing');
INSERT INTO `movement` (id, name) VALUES (14, 'Lunge');
INSERT INTO `movement` (id, name) VALUES (15, 'Burpee');
INSERT INTO `movement` (id, name) VALUES (16, 'Dips');
INSERT INTO `movement` (id, name) VALUES (17, 'Kettlebell Swing');
INSERT INTO `movement` (id, name) VALUES (18, 'Plank');
INSERT INTO `movement` (id, name) VALUES (19, 'Sit-up');
INSERT INTO `movement` (id, name) VALUES (20, 'Run');
INSERT INTO `movement` (id, name) VALUES (21, 'Deadlift_01');
INSERT INTO `movement` (id, name) VALUES (22, 'Back Squat_01');
INSERT INTO `movement` (id, name) VALUES (23, 'Bench Press_01');
INSERT INTO `movement` (id, name) VALUES (24, 'Snatch_01');
INSERT INTO `movement` (id, name) VALUES (25, 'Clean and Jerk_01');
INSERT INTO `movement` (id, name) VALUES (26, 'Front Squat_01');
INSERT INTO `movement` (id, name) VALUES (27, 'Overhead Press_01');
INSERT INTO `movement` (id, name) VALUES (28, 'Pull-up_01');
INSERT INTO `movement` (id, name) VALUES (29, 'Push-up_01');
INSERT INTO `movement` (id, name) VALUES (30, 'Row_01');
INSERT INTO `movement` (id, name) VALUES (31, 'Sprint_01');
INSERT INTO `movement` (id, name) VALUES (32, 'Jump_01');
INSERT INTO `movement` (id, name) VALUES (33, 'Swing_01');
INSERT INTO `movement` (id, name) VALUES (34, 'Lunge_01');
INSERT INTO `movement` (id, name) VALUES (35, 'Burpee_01');
INSERT INTO `movement` (id, name) VALUES (36, 'Dips_01');
INSERT INTO `movement` (id, name) VALUES (37, 'Kettlebell Swing_01');
INSERT INTO `movement` (id, name) VALUES (38, 'Plank_01');
INSERT INTO `movement` (id, name) VALUES (39, 'Sit-up_01');
INSERT INTO `movement` (id, name) VALUES (40, 'Run_01');
INSERT INTO `movement` (id, name) VALUES (41, 'Deadlift_02');
INSERT INTO `movement` (id, name) VALUES (42, 'Back Squat_02');
INSERT INTO `movement` (id, name) VALUES (43, 'Bench Press_02');
INSERT INTO `movement` (id, name) VALUES (44, 'Snatch_02');
INSERT INTO `movement` (id, name) VALUES (45, 'Clean and Jerk_02');
INSERT INTO `movement` (id, name) VALUES (46, 'Front Squat_02');
INSERT INTO `movement` (id, name) VALUES (47, 'Overhead Press_02');
INSERT INTO `movement` (id, name) VALUES (48, 'Pull-up_02');
INSERT INTO `movement` (id, name) VALUES (49, 'Push-up_02');
INSERT INTO `movement` (id, name) VALUES (50, 'Row_02');
INSERT INTO `movement` (id, name) VALUES (51, 'Sprint_02');
INSERT INTO `movement` (id, name) VALUES (52, 'Jump_02');
INSERT INTO `movement` (id, name) VALUES (53, 'Swing_02');
INSERT INTO `movement` (id, name) VALUES (54, 'Lunge_02');
INSERT INTO `movement` (id, name) VALUES (55, 'Burpee_02');
INSERT INTO `movement` (id, name) VALUES (56, 'Dips_02');
INSERT INTO `movement` (id, name) VALUES (57, 'Kettlebell Swing_02');
INSERT INTO `movement` (id, name) VALUES (58, 'Plank_02');
INSERT INTO `movement` (id, name) VALUES (59, 'Sit-up_02');
INSERT INTO `movement` (id, name) VALUES (60, 'Run_02');
INSERT INTO `movement` (id, name) VALUES (61, 'Deadlift_03');
INSERT INTO `movement` (id, name) VALUES (62, 'Back Squat_03');
INSERT INTO `movement` (id, name) VALUES (63, 'Bench Press_03');
INSERT INTO `movement` (id, name) VALUES (64, 'Snatch_03');
INSERT INTO `movement` (id, name) VALUES (65, 'Clean and Jerk_03');
INSERT INTO `movement` (id, name) VALUES (66, 'Front Squat_03');
INSERT INTO `movement` (id, name) VALUES (67, 'Overhead Press_03');
INSERT INTO `movement` (id, name) VALUES (68, 'Pull-up_03');
INSERT INTO `movement` (id, name) VALUES (69, 'Push-up_03');
INSERT INTO `movement` (id, name) VALUES (70, 'Row_03');
INSERT INTO `movement` (id, name) VALUES (71, 'Sprint_03');
INSERT INTO `movement` (id, name) VALUES (72, 'Jump_03');
INSERT INTO `movement` (id, name) VALUES (73, 'Swing_03');
INSERT INTO `movement` (id, name) VALUES (74, 'Lunge_03');
INSERT INTO `movement` (id, name) VALUES (75, 'Burpee_03');
INSERT INTO `movement` (id, name) VALUES (76, 'Dips_03');
INSERT INTO `movement` (id, name) VALUES (77, 'Kettlebell Swing_03');
INSERT INTO `movement` (id, name) VALUES (78, 'Plank_03');
INSERT INTO `movement` (id, name) VALUES (79, 'Sit-up_03');
INSERT INTO `movement` (id, name) VALUES (80, 'Run_03');
INSERT INTO `movement` (id, name) VALUES (81, 'Deadlift_04');
INSERT INTO `movement` (id, name) VALUES (82, 'Back Squat_04');
INSERT INTO `movement` (id, name) VALUES (83, 'Bench Press_04');
INSERT INTO `movement` (id, name) VALUES (84, 'Snatch_04');
INSERT INTO `movement` (id, name) VALUES (85, 'Clean and Jerk_04');
INSERT INTO `movement` (id, name) VALUES (86, 'Front Squat_04');
INSERT INTO `movement` (id, name) VALUES (87, 'Overhead Press_04');
INSERT INTO `movement` (id, name) VALUES (88, 'Pull-up_04');
INSERT INTO `movement` (id, name) VALUES (89, 'Push-up_04');
INSERT INTO `movement` (id, name) VALUES (90, 'Row_04');
INSERT INTO `movement` (id, name) VALUES (91, 'Sprint_04');
INSERT INTO `movement` (id, name) VALUES (92, 'Jump_04');
INSERT INTO `movement` (id, name) VALUES (93, 'Swing_04');
INSERT INTO `movement` (id, name) VALUES (94, 'Lunge_04');
INSERT INTO `movement` (id, name) VALUES (95, 'Burpee_04');
INSERT INTO `movement` (id, name) VALUES (96, 'Dips_04');
INSERT INTO `movement` (id, name) VALUES (97, 'Kettlebell Swing_04');
INSERT INTO `movement` (id, name) VALUES (98, 'Plank_04');
INSERT INTO `movement` (id, name) VALUES (99, 'Sit-up_04');
INSERT INTO `movement` (id, name) VALUES (100, 'Run_04');
INSERT INTO `movement` (id, name) VALUES (101, 'Deadlift_05');
INSERT INTO `movement` (id, name) VALUES (102, 'Back Squat_05');
INSERT INTO `movement` (id, name) VALUES (103, 'Bench Press_05');
INSERT INTO `movement` (id, name) VALUES (104, 'Snatch_05');
INSERT INTO `movement` (id, name) VALUES (105, 'Clean and Jerk_05');
INSERT INTO `movement` (id, name) VALUES (106, 'Front Squat_05');
INSERT INTO `movement` (id, name) VALUES (107, 'Overhead Press_05');
INSERT INTO `movement` (id, name) VALUES (108, 'Pull-up_05');
INSERT INTO `movement` (id, name) VALUES (109, 'Push-up_05');
INSERT INTO `movement` (id, name) VALUES (110, 'Row_05');
INSERT INTO `movement` (id, name) VALUES (111, 'Sprint_05');
INSERT INTO `movement` (id, name) VALUES (112, 'Jump_05');
INSERT INTO `movement` (id, name) VALUES (113, 'Swing_05');
INSERT INTO `movement` (id, name) VALUES (114, 'Lunge_05');
INSERT INTO `movement` (id, name) VALUES (115, 'Burpee_05');
INSERT INTO `movement` (id, name) VALUES (116, 'Dips_05');
INSERT INTO `movement` (id, name) VALUES (117, 'Kettlebell Swing_05');
INSERT INTO `movement` (id, name) VALUES (118, 'Plank_05');
INSERT INTO `movement` (id, name) VALUES (119, 'Sit-up_05');
INSERT INTO `movement` (id, name) VALUES (120, 'Run_05');
INSERT INTO `movement` (id, name) VALUES (121, 'Deadlift_06');
INSERT INTO `movement` (id, name) VALUES (122, 'Back Squat_06');
INSERT INTO `movement` (id, name) VALUES (123, 'Bench Press_06');
INSERT INTO `movement` (id, name) VALUES (124, 'Snatch_06');
INSERT INTO `movement` (id, name) VALUES (125, 'Clean and Jerk_06');
INSERT INTO `movement` (id, name) VALUES (126, 'Front Squat_06');
INSERT INTO `movement` (id, name) VALUES (127, 'Overhead Press_06');
INSERT INTO `movement` (id, name) VALUES (128, 'Pull-up_06');
INSERT INTO `movement` (id, name) VALUES (129, 'Push-up_06');
INSERT INTO `movement` (id, name) VALUES (130, 'Row_06');
INSERT INTO `movement` (id, name) VALUES (131, 'Sprint_06');
INSERT INTO `movement` (id, name) VALUES (132, 'Jump_06');
INSERT INTO `movement` (id, name) VALUES (133, 'Swing_06');
INSERT INTO `movement` (id, name) VALUES (134, 'Lunge_06');
INSERT INTO `movement` (id, name) VALUES (135, 'Burpee_06');
INSERT INTO `movement` (id, name) VALUES (136, 'Dips_06');
INSERT INTO `movement` (id, name) VALUES (137, 'Kettlebell Swing_06');
INSERT INTO `movement` (id, name) VALUES (138, 'Plank_06');
INSERT INTO `movement` (id, name) VALUES (139, 'Sit-up_06');
INSERT INTO `movement` (id, name) VALUES (140, 'Run_06');
INSERT INTO `movement` (id, name) VALUES (141, 'Deadlift_07');
INSERT INTO `movement` (id, name) VALUES (142, 'Back Squat_07');
INSERT INTO `movement` (id, name) VALUES (143, 'Bench Press_07');
INSERT INTO `movement` (id, name) VALUES (144, 'Snatch_07');
INSERT INTO `movement` (id, name) VALUES (145, 'Clean and Jerk_07');
INSERT INTO `movement` (id, name) VALUES (146, 'Front Squat_07');
INSERT INTO `movement` (id, name) VALUES (147, 'Overhead Press_07');
INSERT INTO `movement` (id, name) VALUES (148, 'Pull-up_07');
INSERT INTO `movement` (id, name) VALUES (149, 'Push-up_07');
INSERT INTO `movement` (id, name) VALUES (150, 'Row_07');
INSERT INTO `movement` (id, name) VALUES (151, 'Sprint_07');
INSERT INTO `movement` (id, name) VALUES (152, 'Jump_07');
INSERT INTO `movement` (id, name) VALUES (153, 'Swing_07');
INSERT INTO `movement` (id, name) VALUES (154, 'Lunge_07');
INSERT INTO `movement` (id, name) VALUES (155, 'Burpee_07');
INSERT INTO `movement` (id, name) VALUES (156, 'Dips_07');
INSERT INTO `movement` (id, name) VALUES (157, 'Kettlebell Swing_07');
INSERT INTO `movement` (id, name) VALUES (158, 'Plank_07');
INSERT INTO `movement` (id, name) VALUES (159, 'Sit-up_07');
INSERT INTO `movement` (id, name) VALUES (160, 'Run_07');
INSERT INTO `movement` (id, name) VALUES (161, 'Deadlift_08');
INSERT INTO `movement` (id, name) VALUES (162, 'Back Squat_08');
INSERT INTO `movement` (id, name) VALUES (163, 'Bench Press_08');
INSERT INTO `movement` (id, name) VALUES (164, 'Snatch_08');
INSERT INTO `movement` (id, name) VALUES (165, 'Clean and Jerk_08');
INSERT INTO `movement` (id, name) VALUES (166, 'Front Squat_08');
INSERT INTO `movement` (id, name) VALUES (167, 'Overhead Press_08');
INSERT INTO `movement` (id, name) VALUES (168, 'Pull-up_08');
INSERT INTO `movement` (id, name) VALUES (169, 'Push-up_08');
INSERT INTO `movement` (id, name) VALUES (170, 'Row_08');
INSERT INTO `movement` (id, name) VALUES (171, 'Sprint_08');
INSERT INTO `movement` (id, name) VALUES (172, 'Jump_08');
INSERT INTO `movement` (id, name) VALUES (173, 'Swing_08');
INSERT INTO `movement` (id, name) VALUES (174, 'Lunge_08');
INSERT INTO `movement` (id, name) VALUES (175, 'Burpee_08');
INSERT INTO `movement` (id, name) VALUES (176, 'Dips_08');
INSERT INTO `movement` (id, name) VALUES (177, 'Kettlebell Swing_08');
INSERT INTO `movement` (id, name) VALUES (178, 'Plank_08');
INSERT INTO `movement` (id, name) VALUES (179, 'Sit-up_08');
INSERT INTO `movement` (id, name) VALUES (180, 'Run_08');
INSERT INTO `movement` (id, name) VALUES (181, 'Deadlift_09');
INSERT INTO `movement` (id, name) VALUES (182, 'Back Squat_09');
INSERT INTO `movement` (id, name) VALUES (183, 'Bench Press_09');
INSERT INTO `movement` (id, name) VALUES (184, 'Snatch_09');
INSERT INTO `movement` (id, name) VALUES (185, 'Clean and Jerk_09');
INSERT INTO `movement` (id, name) VALUES (186, 'Front Squat_09');
INSERT INTO `movement` (id, name) VALUES (187, 'Overhead Press_09');
INSERT INTO `movement` (id, name) VALUES (188, 'Pull-up_09');
INSERT INTO `movement` (id, name) VALUES (189, 'Push-up_09');
INSERT INTO `movement` (id, name) VALUES (190, 'Row_09');
INSERT INTO `movement` (id, name) VALUES (191, 'Sprint_09');
INSERT INTO `movement` (id, name) VALUES (192, 'Jump_09');
INSERT INTO `movement` (id, name) VALUES (193, 'Swing_09');
INSERT INTO `movement` (id, name) VALUES (194, 'Lunge_09');
INSERT INTO `movement` (id, name) VALUES (195, 'Burpee_09');
INSERT INTO `movement` (id, name) VALUES (196, 'Dips_09');
INSERT INTO `movement` (id, name) VALUES (197, 'Kettlebell Swing_09');
INSERT INTO `movement` (id, name) VALUES (198, 'Plank_09');
INSERT INTO `movement` (id, name) VALUES (199, 'Sit-up_09');
INSERT INTO `movement` (id, name) VALUES (200, 'Run_09');
INSERT INTO `movement` (id, name) VALUES (201, 'Deadlift_10');
INSERT INTO `movement` (id, name) VALUES (202, 'Back Squat_10');
INSERT INTO `movement` (id, name) VALUES (203, 'Bench Press_10');
INSERT INTO `movement` (id, name) VALUES (204, 'Snatch_10');
INSERT INTO `movement` (id, name) VALUES (205, 'Clean and Jerk_10');
INSERT INTO `movement` (id, name) VALUES (206, 'Front Squat_10');
INSERT INTO `movement` (id, name) VALUES (207, 'Overhead Press_10');
INSERT INTO `movement` (id, name) VALUES (208, 'Pull-up_10');
INSERT INTO `movement` (id, name) VALUES (209, 'Push-up_10');
INSERT INTO `movement` (id, name) VALUES (210, 'Row_10');
INSERT INTO `movement` (id, name) VALUES (211, 'Sprint_10');
INSERT INTO `movement` (id, name) VALUES (212, 'Jump_10');
INSERT INTO `movement` (id, name) VALUES (213, 'Swing_10');
INSERT INTO `movement` (id, name) VALUES (214, 'Lunge_10');
INSERT INTO `movement` (id, name) VALUES (215, 'Burpee_10');
INSERT INTO `movement` (id, name) VALUES (216, 'Dips_10');
INSERT INTO `movement` (id, name) VALUES (217, 'Kettlebell Swing_10');
INSERT INTO `movement` (id, name) VALUES (218, 'Plank_10');
INSERT INTO `movement` (id, name) VALUES (219, 'Sit-up_10');
INSERT INTO `movement` (id, name) VALUES (220, 'Run_10');